#!/usr/bin/env bash
set -e

MANAGER="${POSTGRES_DB_NAME}_manager"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE $POSTGRES_DB_NAME;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB_NAME" <<-EOSQL
	CREATE ROLE $MANAGER NOLOGIN;
	CREATE USER $POSTGRES_DB_USER WITH PASSWORD '$POSTGRES_DB_PASSWORD';
	ALTER SCHEMA public OWNER TO $MANAGER;
	GRANT USAGE, CREATE ON SCHEMA public TO $MANAGER;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $MANAGER;
	GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $MANAGER;
	GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $MANAGER;
	ALTER DEFAULT PRIVILEGES FOR ROLE $MANAGER IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO $MANAGER;
	ALTER DEFAULT PRIVILEGES FOR ROLE $MANAGER IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO $MANAGER;
	ALTER DEFAULT PRIVILEGES FOR ROLE $MANAGER IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO $MANAGER;
	GRANT $MANAGER TO $POSTGRES_DB_USER;
EOSQL
